---
galaxy_info:
  author: Chad Ferman
  description: Pre-upgrade health check for AAP on OpenShift
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - aap
    - openshift
    - kubernetes
    - upgrade
    - validation

dependencies: []
