---
- name: Check chadsno2026 AAP Deployment
  hosts: localhost
  gather_facts: true

  vars:
    aap_kubeconfig_path: ~/.kube/kubeconfig-noingress
    aap_namespace: ansible-automation-platform
    aap_database_namespace: edb-pg-demo
    aap_report_filename: "chadsno2026-pre-upgrade-{{ ansible_date_time.iso8601_basic_short }}.md"

  roles:
    - aap_pre_upgrade_check
